baseURL = "https://www.aljanscholtens.nl/"
title = "Aljan Scholtens"
languageCode = "nl"
paginate = 3

[params]
author = "Aljan"

defaultContentLanguage = "nl"

[languages]
[languages.nl]
  languageName = "Nederlands"
  weight = 1
  contentDir = "content"
  lang = "nl"
  languageDirection = "ltr"

[languages.en]
  languageName = "English"
  weight = 2
  contentDir = "content"
  lang = "en"
  languageDirection = "ltr"

enableInlineShortcodes = true
defaultContentLanguageInSubdir = false