baseURL = "https://example.com/"
title = "Mijn Hugo Site"
languageCode = "nl"
paginate = 3

[params]
author = "Aljan"

defaultContentLanguage = "nl"
[languages]
[languages.nl]
  languageName = "Nederlands"
  contentDir = "content"
[languages.en]
  languageName = "English"
  contentDir = "content"