

baseURL = "https://www.aljanscholtens.nl/"
title = "Aljan Scholtens"
languageCode = "nl"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false
paginate = 3

[params]
  author = "Aljan"

[languages]

  [languages.nl]
    languageName = "Nederlands"
    weight = 1
    contentDir = "content"
    lang = "nl"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content"
    lang = "en"

  